name: brasil_cripto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  get_it: ^8.0.3
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  rxdart: ^0.28.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
